import Joi from '@hapi/joi';

export const optionsShowdownSchema = Joi.object({
    omitExtraWLInCodeBlocks: Joi.boolean(),
    noHeaderId: Joi.boolean(),
    customizedHeaderId: Joi.boolean(),
    ghCompatibleHeaderId: Joi.boolean(),
    prefixHeaderId: Joi.alternatives(Joi.boolean(), Joi.string().max(32)),
    rawPrefixHeaderId: Joi.boolean(),
    rawHeaderId: Joi.boolean(),
    parseImgDimensions: Joi.boolean(),
    headerLevelStart: Joi.number().positive().integer().min(1).max(6),
    simplifiedAutoLink: Joi.boolean(),
    excludeTrailingPunctuationFromURLs: Joi.boolean(),
    literalMidWordUnderscores: Joi.boolean(),
    strikethrough: Joi.boolean(),
    tables: Joi.boolean(),
    ghCodeBlocks: Joi.boolean(),
    tasklists: Joi.boolean(),
    smoothLivePreview: Joi.boolean(),
    smartIndentationFix: Joi.boolean(),
    disableForced4SpacesIndentedSublists: Joi.boolean(),
    simpleLineBreaks: Joi.boolean(),
    requireSpaceBeforeHeadingText: Joi.boolean(),
    ghMentions: Joi.boolean(),
    ghMentionsLink: Joi.boolean(),
    encodeEmails: Joi.boolean(),
    openLinksInNewWindow: Joi.boolean(),
    backslashEscapesHTMLTags: Joi.boolean(),
    emoji: Joi.boolean(),
    underline: Joi.boolean(),
    completeHTMLDocument: Joi.boolean(),
    metadata: Joi.boolean(),
    splitAdjacentBlockquotes: Joi.boolean(),
}).required();
