export const TYPES = {
    AppBuilder: Symbol('appBuilder'),
    JwtTokenOptions: Symbol('tokenOptions'),
    JwtTokenService: Symbol('tokenService'),
    LogService: Symbol('logService'),
    UserContextFactory: Symbol('userContextFactory'),
    UserService: Symbol('userService'),
    AuthMiddleware: Symbol('authMiddleware'),
    JoiValidationMiddlewareFactory: Symbol('joiValidationMiddlewareFactory'),
    QueryParseMiddlewareFactory: Symbol('queryParseMiddlewareFactory'),
    UserAuthorizeMiddlewareFactory: Symbol('userAuthorizeMiddlewareFactory'),
    RouteTokenController: Symbol('routeTokenController'),
    RouteEchoController: Symbol('routeEchoController'),
    RouteUserController: Symbol('routeUserController'),
    RouteControllers: Symbol('routeCOntrollers'),
    ModelUser: Symbol('modelUser'),
    ModelRefreshToken: Symbol('modelRefreshToken'),
    ModelLog: Symbol('modelLog'),
};
